In [34]:
import numpy as np

A = np.random.rand(3,4)

In [35]:
A

array([[0.67508317, 0.16839511, 0.63945971, 0.46335839],
       [0.66546684, 0.74031439, 0.39716217, 0.67052716],
       [0.54028778, 0.85554109, 0.90767258, 0.40912672]])

In [36]:
a=A[0:3,0:3]
b=A[:,3]

In [37]:
print(a,b)

[[0.67508317 0.16839511 0.63945971]
 [0.66546684 0.74031439 0.39716217]
 [0.54028778 0.85554109 0.90767258]] [0.46335839 0.67052716 0.40912672]


In [38]:
n=len(a)

In [10]:
aa=a.copy()

In [31]:
a=np.array([[1,1,1],
            [2,1,2],
            [3,1,4]])
n=3

In [49]:
A = np.random.rand(3,4)
a=A[0:3,0:3]
b=A[:,3]
n=len(a)
x=np.zeros(len(b))
aa=a.copy()
bb=b.copy()

In [50]:
#elimination phase (상삼각행렬 만들기)
for  k in range(0,n-1): #pivot rows 1~n-1까지
  for i in range(k+1,n):
    if a[i,k] != 0:
      print('we are in the loop',i,k)
      lam = a[i,k]/a[k,k] #defintion of lambda
      #a[i,k]=0
      a[i,k:n]=a[i,k:n] - lam*a[k,k:n]
      b[i]=b[i]-lam*b[k]

#Back substitiution

for k in range(n-1,-1,-1):
  x[k]=(b[k]-np.dot(a[k,k+1:n],x[k+1:n]))/a[k,k]


we are in the loop 1 0
we are in the loop 2 0
we are in the loop 2 1


In [54]:
def gauss(a,b):
    # elimination phase (상삼각행렬 만들기)
    for k in range(0, n - 1):  # pivot rows 1~n-1까지
        for i in range(k + 1, n):
            if a[i, k] != 0:
                #print('we are in the loop', i, k)
                lam = a[i, k] / a[k, k]  # defintion of lambda
                # a[i,k]=0
                a[i, k:n] = a[i, k:n] - lam * a[k, k:n]
                b[i] = b[i] - lam * b[k]

    # Back substitiution

    for k in range(n - 1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k + 1:n], x[k + 1:n])) / a[k, k]
    return x

In [51]:
x

array([-0.02310832, -0.96560845,  1.4499672 ])

In [55]:
gauss(a,b)

we are in the loop 2 1


array([-0.02310832, -0.96560845,  1.4499672 ])

In [53]:
np.linalg.solve(aa,bb)

array([-0.02310832, -0.96560845,  1.4499672 ])

In [48]:
print(f'before\n {aa} \n\n after\n {a}')
print(f'before\n {bb} \n\n after\n {b}')

before
 [[0.2389236  0.15884317 0.04045626]
 [0.21753522 0.55935778 0.40259883]
 [0.01088038 0.17286912 0.28239015]] 

 after
 [[0.2389236  0.15884317 0.04045626]
 [0.         0.4147342  0.36576421]
 [0.         0.         0.13446979]]
before
 [0.29885307 0.14589836 0.46230826] 

 after
 [0.29885307 0.14589836 0.46230826]


In [19]:
 %time

 A=np.zeros((4000,4000))
 for i in range(4000):
   for j in range(4000):
     A[i,j]+=1

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.39 µs


In [20]:
%time

A=np.zeros((4000,4000))
A+=np.ones((4000,4000))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.72 µs


In [70]:
A = np.random.rand(3,4)
a=A[0:3,0:3]
b=A[:,3]
n=len(a)
x=np.zeros(len(b))
aa=a.copy()
bb=b.copy()

In [71]:
#elimination phase (하삼각행렬 만들기)
for  k in range(n-1,0,-1): #pivot rows n-1 ~ 1까지
  for i in range(k-1,-1,-1):
    if a[i,k] != 0:
      print('we are in the loop',i,k)
      lam = a[i,k]/a[k,k] #defintion of lambda
      #a[i,k]=0
      a[i,0:k+1]=a[i,0:k+1] - lam*a[k,0:k+1]
      b[i]=b[i]-lam*b[k]

#Back substitiution

for k in range(0,n):
  x[k]=(b[k]-np.dot(a[k,0:k],x[0:k]))/a[k,k]

we are in the loop 1 2
we are in the loop 0 2
we are in the loop 0 1


In [72]:
a

array([[ 2.13698487e+01,  0.00000000e+00,  0.00000000e+00],
       [ 2.61150387e-01, -7.71963646e-03,  0.00000000e+00],
       [ 6.97900233e-01,  3.13109003e-02,  5.37392456e-01]])

In [73]:
x

array([ 1.50013897,  0.27979643, -0.75020796])

In [75]:
np.linalg.solve(aa,bb)

array([ 1.50013897,  0.27979643, -0.75020796])

In [79]:
bmat=np.array([[1,2],
               [2,3],
               [3,4]])

bmat.shape[1]

2

In [94]:
def gauss2(a,b):
    b_n=bmat.shape[1]
    x=np.zeros(bmat.shape)
    # elimination phase (상삼각행렬 만들기)
    for k in range(0, n - 1):  # pivot rows 1~n-1까지
        for i in range(k + 1, n):
            if a[i, k] != 0:
                #print('we are in the loop', i, k)
                lam = a[i, k] / a[k, k]  # defintion of lambda
                # a[i,k]=0
                a[i, k:n] = a[i, k:n] - lam * a[k, k:n]
                b[i,:] = b[i,:] - lam * b[k,:]

    # Back substitiution

    for k in range(n - 1, -1, -1):
        for m in range(b_n):
          print(k,m)
          x[k,m] = (b[k,m] - np.dot(a[k, k + 1:n], x[k + 1:n])) / a[k, k]
    return x

In [95]:
gauss2(aa,bmat)

2 0


ValueError: ignored

In [84]:
x=np.zeros(bmat.shape)

In [85]:
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])