In [ ]:
import os

In [ ]:
os.chdir('/content/drive/MyDrive/21-1/Computational Physics')

In [ ]:
from ch2 import *

In [ ]:
from scipy.linalg import lu_factor,lu_solve
A=np.array([[3,-3,3],[-3,5,1],[3,1,5]],dtype=float)
B=np.array([9,-7,12],dtype=float)
lu_factor(A)

(array([[ 3. , -3. ,  3. ],
        [ 1. ,  4. ,  2. ],
        [-1. ,  0.5,  3. ]]), array([0, 2, 2], dtype=int32))

In [ ]:
LU=LUdecomp(A)
x=LUsolve(LU,B)
print(x)

[3.5        0.66666667 0.16666667]


In [30]:
A=np.array([[4,8,20],[8,13,16],[20,16,-91]],dtype=float)
B=np.array([24,18,-119],dtype=float)

LU=LUdecomp(A)
x=LUsolve(LU,B)
print(x)
print(B)
np.linalg.solve(A,B)

[-3.  2.  1.]
[-3.  2.  1.]


array([-0.9875,  0.775 , -0.2625])

In [ ]:
#sparse matrix,tridiagonal
A=np.array([[2,-2,0,0,0],[-2,5,6,0,0],[0,-6,16,12,0],[0,0,12,39,-6],[0,0,0,-6,14]])

In [76]:
#3X3
# c=np.ones(2)
# e=2*np.ones(2)
# d=4*np.ones(3)
n=10
c=np.ones(n-1)
e=2*np.ones(n-1)
d=4*np.ones(n)

D=np.diag(d)
E=np.diag(e,k=1)
C=np.diag(c,k=-1)
A=C+D+E
b=np.ones(n)

In [ ]:
D=np.diag(d)
D

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [ ]:
E=np.diag(e,k=1)
E

array([[0., 2., 0.],
       [0., 0., 2.],
       [0., 0., 0.]])

In [ ]:
C=np.diag(c,k=-1)
C

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
A=C+D+E
A

array([[4., 2., 0.],
       [1., 4., 2.],
       [0., 1., 4.]])

In [77]:
y=np.zeros(n)
x=np.zeros(n)

for k in range(1,n): #두번째 행부터 끝까지
  lam=c[k-1]/d[k-1]
  d[k] = d[k]-lam*e[k-1]
  c[k-1]=lam

#L@y=b forward
y[0] = b[0]
for k in range(1,n):
  y[k]=b[k]-c[k-1]*y[k-1]

#U@x=y backward
x[n-1]=y[n-1]/d[n-1]
for k in range(n-2,-1,-1):
  x[k]=(y[k]-e[k]*x[k+1])/d[k]


In [78]:
x

array([0.18413598, 0.13172805, 0.14447592, 0.14518414, 0.13739377,
       0.1526204 , 0.12606232, 0.17156516, 0.09383853, 0.22654037])

In [38]:
np.linalg.solve(A,b)

array([0.18413598, 0.13172805, 0.14447592, 0.14518414, 0.13739377,
       0.1526204 , 0.12606232, 0.17156516, 0.09383853, 0.22654037])

In [79]:
A@x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [87]:
n=5
d=2*np.ones(5)
c=np.ones(4)
e=np.ones(4)

In [88]:
D=np.diag(d)

In [89]:
C=np.diag(c,k=-1)

In [90]:
E=np.diag(e,k=1)

In [91]:
A=C+D+E
b=np.ones(5)

In [92]:
for k in range(1,n): #두번째 행부터 끝까지
  lam=c[k-1]/d[k-1]
  d[k] = d[k]-lam*e[k-1]
  c[k-1]=lam

In [93]:
L=np.eye(5)+np.diag(c,k=-1)
L

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.5       , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.66666667, 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.75      , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.8       , 1.        ]])

In [94]:
U=np.diag(d)+np.diag(e,k=1)
U

array([[2.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 1.5       , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.33333333, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.25      , 1.        ],
       [0.        , 0.        , 0.        , 0.        , 1.2       ]])

In [95]:
#L@y=b forward
y=np.zeros(n)
x=np.zeros(n)
y[0] = b[0]
for k in range(1,n):
  y[k]=b[k]-c[k-1]*y[k-1]

#U@x=y backward
x[n-1]=y[n-1]/d[n-1]
for k in range(n-2,-1,-1):
  x[k]=(y[k]-e[k]*x[k+1])/d[k]

In [96]:
x

array([0.5, 0. , 0.5, 0. , 0.5])

In [97]:
np.linalg.solve(A,b)

array([0.5, 0. , 0.5, 0. , 0.5])