In [1]:
import numpy as np

In [20]:
#1
n=1000
3*np.eye(n,k=1)+2*np.eye(n)+np.eye(n,k=-1)

array([[2., 3., 0., ..., 0., 0., 0.],
       [1., 2., 3., ..., 0., 0., 0.],
       [0., 1., 2., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 2., 3., 0.],
       [0., 0., 0., ..., 1., 2., 3.],
       [0., 0., 0., ..., 0., 1., 2.]])

In [3]:
#2
A=np.array([[1,2],
            [1,-3]])
b=np.array([10,5])
np.linalg.solve(A,b)

array([8., 1.])

In [15]:
#3
'''
s+2p+d+0+0=5
2s-p-3d+0+0=7
2s+0+0-f-2g=4
0+2p+0-2f+g=2
0+0+2d-f+3g=0
'''
A=np.array([[1,2,1,0,0],
            [2,-1,-3,0,0],
            [2,0,0,-1,-2],
            [0,2,0,-2,1],
            [0,0,2,-1,3]])
b=np.array([5,7,4,2,0])
np.linalg.solve(A,b)

array([ 3.06666667,  1.33333333, -0.73333333,  0.69333333,  0.72      ])

In [14]:
#4
from math import sin,cos,pi
angle=20*(pi/180)
A=np.array([[cos(angle),-1*sin(angle)],
            [sin(angle),cos(angle)]])
b=np.array([1,0])
np.dot(A,b)

array([0.93969262, 0.34202014])

In [30]:
#5
a1=np.array([2.46,0.00,0.00])
a2=np.array([-1.23,2.14,0.00])
a3=np.array([0.00,0.00,10.00])
A=np.vstack([a1,a2,a3])
b1=np.array([1,0,0])
b2=np.array([0,1,0])
b3=np.array([0,0,1])

v1=np.linalg.solve(A,b1)
v2=np.linalg.solve(A,b2)
v3=np.linalg.solve(A,b3)

print(f'v1:{v1} \nv2:{v2} \nv3:{v3}')

v1:[0.40650407 0.23364486 0.        ] 
v2:[0.         0.46728972 0.        ] 
v3:[0.  0.  0.1]
