In [1]:
import numpy as np

In [2]:
#1
def backwdsub(A,b):
  n=len(b)
  for k in range(n-1,-1,-1):
    b[k]=(b[k]-np.dot(A[k,k+1:n],b[k+1:n]))/A[k,k]
  return b

In [ ]:
#2-1
'''
x1=1
x2=1
x1+x2=x3
x2+x3=x4
x3+x4=x5

[[1,0,0,0,0],
 [0,1,0,0,0],
 [1,1,-1,0,0],
 [0,1,1,-1,0],
 [0,0,1,1,-1]]
 '''

In [94]:
#2-2
A3_10=np.eye(8)+np.eye(8,k=1)-np.eye(8,k=2)
k=np.zeros([8,2])
k[6,0]=-1
k[7,0]=1
k[7,1]=-1
A3_10=np.hstack([A3_10,k])

In [96]:
A1_2=np.zeros([2,10])
A1_2[0,0]=1
A1_2[1,1]=1
A=np.vstack([A1_2,A3_10])

In [97]:
A

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  1., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1., -1.]])

In [98]:
b=np.zeros(10)
b[0]=1
b[1]=1

In [99]:
b

array([1., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [103]:
#2-3
def forwardsub(A,b):
  n=len(b)
  for k in range(0,n):
    b[k]=(b[k]-np.dot(A[k,:k],b[:k]))/A[k,k]
  return b

In [104]:
forwardsub(A,b)

array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])

In [105]:
#3-1
A=np.array([[0.95,0.02],
          [0.05,0.98]])

In [66]:
#3-2
lam1=A[1,0]/A[0,0]
A[1]=A[1]-lam1*A[0]

In [67]:
U=A.copy()

In [68]:
lam1

0.052631578947368425

In [69]:
L=np.eye(2)
L[1,0]=lam1

In [70]:
L@U

array([[0.95, 0.02],
       [0.05, 0.98]])

In [71]:
U

array([[0.95      , 0.02      ],
       [0.        , 0.97894737]])

In [72]:
L

array([[1.        , 0.        ],
       [0.05263158, 1.        ]])

In [63]:
#3-3
def ans(L,U,b):
#L@y=b
  y=np.zeros(2)
  y[0]=b[0]
  y[1]=b[1]-b[0]*L[1,0]

#U@x=y
  x=np.zeros(2)
  x[1]=y[1]/U[1,1]
  x[0]=(y[0]-y[1]*U[0,1])/U[0,0]
  return x

In [61]:
b=np.array([30,24])

In [76]:
b2020=ans(L,U,b)
b2019=ans(L,U,b2020)
b2018=ans(L,U,b2019)

In [77]:
b2018

array([33.5746898 , 20.45415485])

In [110]:
print(f'A인구 :{b2018[0] :.3f}만명, B인구:{b2018[1]:.3f}만명')

A인구 :33.575만명, B인구:20.454만명


In [109]:
A@(A@(A@b2018))

array([30.02614112, 24.00270353])