In [1]:
import os
os.chdir('/content/drive/MyDrive/21-1/Computational Physics')

In [2]:
# b=[1,0,0,0,...0]
# A=[2,1,0,..,0]
#   [1,2,1,...0]
#   [0,1,2,..]

In [4]:
import numpy as np
from ch2 import *
#Conjugate Gradient Method

In [9]:
n=5
A=2*np.eye(n)+np.eye(n,k=-1)+np.eye(n,k=1)
b=np.zeros(n)
b[0]=1
print(A,b)



[[2. 1. 0. 0. 0.]
 [1. 2. 1. 0. 0.]
 [0. 1. 2. 1. 0.]
 [0. 0. 1. 2. 1.]
 [0. 0. 0. 1. 2.]] [1. 0. 0. 0. 0.]


In [ ]:
def Av(v):
  global A
  n= len(v)
  x=np.zeros(n)
  x[0] = A[0,0]*v[0] +A[0,1]*v[1]
  x[n-1] = A[n-1,n-2]*v[n-2] +A[n-1,n-1]*v[n-1]
  for i in range(1,n):
    x[i]=A[i,i-1]*v[i-1]+A[i,i]*v[i]+A[i,i+1]*v[i+1]
    return x
  
x=np.zeros(n)
conjGrad(Av,x,b)