In [2]:
import numpy as np
import math,time

In [ ]:
#1
d=[2,4,4,2,3]
A=np.diag(d)-np.eye(5,k=1)-np.eye(5,k=-1)
A[2,4]=-2
A[4,2]=-2
k=2.5
w=1
b=np.array([w/k]*5)
print(A,b)

[[ 2. -1.  0.  0.  0.]
 [-1.  4. -1.  0.  0.]
 [ 0. -1.  4. -1. -2.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0. -2. -1.  3.]] [0.4 0.4 0.4 0.4 0.4]


In [ ]:
np.linalg.solve(A,b)

array([0.56, 0.72, 1.92, 2.24, 2.16])

In [4]:
def conjGrad(n,A,x,b,tol=1.0e-9):
  r=b-A@x
  s=r.copy()
  
  for i in range(n):
    alpha=(s.T@r)/(s.T@A@s)
    x=x+alpha*s
    r=b-A@x
    # print(f'iter:{i}, x:{x}')
    if (math.sqrt(r@r)) < tol:
      # print(math.sqrt(r@r))
      break
    else:
      beta=-1*(r.T@A@s)/(s.T@A@s)
      s=r+beta*s
  return x,i

In [ ]:
x=np.zeros(5)
conjGrad(100,A,x,b)

iter:0, x:[0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]
iter:1, x:[0.91764706 0.54117647 1.29411765 1.29411765 1.29411765]
iter:2, x:[0.68449848 0.65775076 1.70212766 2.09848024 2.09848024]
iter:3, x:[0.56300078 0.71849961 1.91474863 2.25050274 2.1515603 ]
iter:4, x:[0.56 0.72 1.92 2.24 2.16]
8.08254562088053e-16


(array([0.56, 0.72, 1.92, 2.24, 2.16]), 4)

In [ ]:
#2-1

In [ ]:
n=10
A=4*np.eye(n)-np.eye(n,k=1)-np.eye(n,k=-1)
b=5*np.ones(n)
b[0]=9

In [ ]:
#conjugate Gradient
x=np.zeros(n)
start=time.time()
ans=conjGrad(100,A,x,b)
print(time.time()-start)
print(ans)

0.0004291534423828125
(array([2.90191936, 2.60767745, 2.52879042, 2.50748425, 2.50114659,
       2.4971021 , 2.48726181, 2.45194513, 2.3205187 , 1.83012968]), 9)


In [5]:
#gaussElimin
def gaussElimin(a, b):
    n = len(b)
    # Elimination Phase
    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]

    # Back substitution
    for k in range(n-1, -1, -1):
        b[k] = (b[k] - np.dot(a[k,k+1:n], b[k+1:n]))/a[k,k]
    return b

In [ ]:
start=time.time()
ans=gaussElimin(A,b)
print(time.time()-start)
print(ans)

0.0014801025390625
[2.90191936 2.60767745 2.52879042 2.50748425 2.50114659 2.4971021
 2.48726181 2.45194513 2.3205187  1.83012968]


gaussElimin 방식과 conjugate decent 방식 과 답이 소수셋째자리 까지 일치 하였고 시간은 n=10일때 비슷하였다.

In [ ]:
#2-2

In [6]:
n=10000
A=4*np.eye(n)-np.eye(n,k=1)-np.eye(n,k=-1)
b=5*np.ones(n)
b[0]=9

#conjugate Gradient
x=np.zeros(n)
start=time.time()
ans=conjGrad(100,A,x,b)
print('conjugate:',time.time()-start)
print(ans)

start=time.time()
ans=gaussElimin(A,b)
print('gaussElimin:',time.time()-start)
print(ans)

conjugate: 6.632132530212402
(array([2.90192379, 2.60769515, 2.52885683, ..., 2.45190528, 2.32050808,
       1.83012702]), 17)
gaussElimin: 25.152127027511597
[2.90192379 2.60769515 2.52885683 ... 2.45190528 2.32050808 1.83012702]


gaussElimin 방식과 conjugate decent 방식 과 답이 소수셋째자리 까지 일치 하였고 시간은 n=10000일때는 conjugate decent 방식이 더 빨랐다. 

In [ ]:
#3

In [ ]:
A=np.array([[1.,0,1],
            [0,1,0],
            [0,0,1]])
b=np.array([0,0,1.])
x0=np.array([-1,0,0])
s0=np.array([0,0,1])

In [ ]:
np.linalg.solve(A,b)

array([-1.,  0.,  1.])

In [ ]:
r0=b-A@x0
# s0=r0
a0=(s0.T@r0)/(s0.T@A@s0)
x1=x0+a0*s0
x1

array([-1.,  0.,  1.])

1회시행만에 정답에 도달하였다.

In [ ]:
##추가 시행시.. 사용
r1=b-A@x1
b0=-1*(r1.T@A@s0)/(s0.T@A@s0)
s1=r1+b0*s0
a1=(s1.T@r1)/(s1.T@A@s1)
x2=x1+a1*s1
x2

r2=b-A@x2
b1=-1*(r2.T@A@s1)/(s1.T@A@s1)
s2=r2+b1*s1
a2=(s2.T@r2)/(s2.T@A@s2)
x3=x2+a2*s2
x3